dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: jgp99zKI35bU2UFOKqvm4JDYAWdAbngw2AxD5Bm7IPbtd5AfalFbeot7XunU2MhAoBpQ71MsRctjiTbaR2nQsgYoh+efD2tASIoQHet7z9KtxtRz6tRdaNDiOPpXDXICyvZGA9AbIj4ZQaz7bkk7RoljWmMMDooDR0tyF2ytJoufVxHFan8KjAd5O5mZy+RHZy5v27oQ5VZODEzcTVarkVRb3cWfXA189HqynZI5+h2twHQtmtNrXoR7npaolrAcQ/tIGsJT+Pfhnru0xX7mUexHHbFjtQe0lb23q4+oLhr7vC0ZggrGgJtmQaU2mGo/7u8T0tAyQlzZ9UvH9wp5xCWMxxl307tP7eMfoU4Gxoj/ZsmTTvh6uegeal9DvG1rMrvdFXBLneEGfV/g5fKQnwaLx+SgM14hdE3dRsP/rypyyn0GqWJXalMUuXkbhOaSNdSDzuiE+sGo39S6nr3zRtKnChB1m6GhDga4wbAZpciAiYdGKaJM9MzcbkQCQYDkkbuIOrHQjrJo+Zb35zasB1bSWUvHkP+E12h9H1tEq2op3xAnG2OXJic/OBtAJuzE69g9vU9gkMYAzWuJVtK2z9/VF81hFxSa6uDPFAjYg4Bq4hoP9o1GpbTeD6eAoayhsQTbflRCmfu36IhqtsYnai4qL9nJ0iHjOM6Y3MIGtVw=
  file: Gerbers/MNT-106_gerbers.zip
  on:
    repo: w4xzr/MNT-106
  skip_cleanup: 'true'
